#+title: Dotfile Config
#+AUTHOR: Moritz Gleissner
#+DESCRIPTION: This is a description for my dotfiles


* Forword
Welcome to my dotfiles repository. All of the dotfiles and its installation will include [[./.config/hypr/README.org][Hyprland]] as desktop environment and a setup of [[./.config/doom/config.org][Doom Emacs]].

I use Arch on an M1 mac btw 😉 so you should have a good look at the required packages and maybe substitute some of them for there better counterpart, but as far as I'm convinced all of the packages that are being used, none of them isn't capable of running on x86_64 architecture.

* Content List :toc:
- [[#forword][Forword]]
- [[#installation][Installation]]
  - [[#requirements][Requirements]]
  - [[#script][Script]]
  - [[#manual-install][Manual Install]]
- [[#binds][Binds]]

* Installation
** Requirements
Follow [[https://wiki.archlinux.org/title/Installation_guide][Arch Wiki]] and install base Arch if not already done.

** Script
#+begin_src bash :tangle no
curl https://gitlab.gleissner.com/Moritz/dotfiles/-/raw/master/install-dotfiles.sh | bash
#+end_src

** Manual Install
*** 1.Backup
You should always backup existing files.
Have a look at this repository and backup files that you don't want to be lost or overwritten.
My suggestion is to backup you =.config= folder in your HOME directory.

*** 2.Clone The Git
There are two ways you can clone the git:
**** A.The normal way with git clone
1. Clone The Repository:
#+begin_src bash :tangle no
git clone https://gitlab.gleissner.com/Moritz/dotfiles.git
#+end_src
2. Move the files you want to use from =$HOME/dotfiles/*= to =$HOME/*=

**** B.Cloning for futher use of the Version Controll
This will make use of gits bare repository feature.
If you are interested in managing you dotfiles the proper way you should have a look at [[https://www.atlassian.com/git/tutorials/dotfiles][this]].
#+begin_src bash :tangle no
mkdir "$HOME/dotfiles"
git clone --bare https://gitlab.gleissner.com/Moritz/dotfiles.git "$HOME/dotfiles"
git --git-dir=$HOME/dotfiles --work-dir=$HOME checkout master
#+end_src

*** 3.Packages
There are scripts that execute =yay= and a list of the needed packages for some of the modules.

If you want Hyprland you should have a look at [[./.config/hypr/README.org][Hyperland README]] and the listed packages.
You can also just run but some of the packages will certainly not be the best choice for you:
#+begin_src bash :tangle no
bash ~/.config/hypr/install-packages.sh
#+end_src

If you want Doom Emacs you should have a look at [[./.config/doom/config.org][Doom Config]] and the listed packages.
You can also just run but some of the packages will certainly not be the best choice for you:
#+begin_src bash :tangle no
bash ~/.config/doom/install-packages.sh
#+end_src

*** 4.Activate SDDM
My Hyprland Config uses [[https://github.com/sddm/sddm][sddm]] as a login manager.
You should activate it with systemctl if you want to use it too:
#+begin_src bash :tangle no
sudo systemctl enable sddm
sudo systemctl start sddm
#+end_src

*** 5.Doom Emcas
If you wanted Doom Emacs and already installed the packages you should already have base Emacs installed.
Now you need Doom and for that you should have a look at there [[https://github.com/doomemacs/doomemacs][git]] or just follow the steps down below.
#+begin_src bash :tangle no
git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.emacs.d
~/.emacs.d/bin/doom install
~/.emacs.d/bin/doom sync
#+end_src

* Binds
All binds you will need for the desktop environment you will find in [[./.config/hypr/README.org][Hyprland README]] and all bindings you will need inside Doom Emacs you will find in find in [[./.config/doom/config.org][Doom Config]].
