return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "cmake",
        "cpp",
        "css",
        "fish",
        "gitignore",
        "graphql",
        "http",
        "java",
        "kotlin",
        "php",
        "rust",
        "scss",
        "sql",
        "svelte",
        "vue",
        "lua",
        "typescript",
        "python",
        "nix",
        "markdown",
        "markdown_inline",
      },
    },
  },
}
